GET http://localhost:5001/api/order

###

GET http://localhost:5001/api/order/628c97c3e9e990fb2d4737e1

###

POST http://localhost:5001/api/order
Content-Type: application/json

{
    "orderNumber": "obamacare"
   
}


###
PUT http://localhost:5001/api/order/628c9d38c8344f8818d51b84
Content-Type: application/json

{
    "orderNumber": "obamacare2"
   
}


###

DELETE http://localhost:5001/api/order/628c9aee99fb488257ddcbc2
