GET http://localhost:5001/api/user

###
GET http://localhost:5001/api/user/6299bbd762647e8b7e2b176d

###
POST http://localhost:5001/api/user
Content-Type: application/json

{
  "email" : "admin@admin",
  "password": "säkert",
  "isAdmin": true
}

###
PUT http://localhost:5001/api/user/629a03ebd1f2630af0f57011
Content-Type: application/json

{
  "email": "admin@admin",
  "password": "säkert",
  "isAdmin": true
}

###

DELETE http://localhost:5001/api/user/628c8dd2b3eac60aef73974e

###


POST http://localhost:5001/api/user/login
Content-Type: application/json

{   
  "email" : "sabina@sabina",
  "password": "sabina"
}

###

DELETE http://localhost:5001/api/user/logout
