GET http://localhost:5001/api/user

###  Get user by id
GET http://localhost:5001/api/user/id


###  create user, doesn't become admin on create user.
POST http://localhost:5001/api/user
Content-Type: application/json

{
  "email" : "admin@japp",
  "password": "säkert",
  "isAdmin": true
}

###  Update user, can make user into admin.
PUT http://localhost:5001/api/user/id
Content-Type: application/json

{
  "email": "admin@japp",
  "isAdmin": true
}

###   Delete user by id
DELETE http://localhost:5001/api/user/id

###  Login user
POST http://localhost:5001/api/user/login
Content-Type: application/json

{   
  "email" : "admin@japp",
  "password": "säkert"
}

###  Logout user
DELETE http://localhost:5001/api/user/logout
