GET http://localhost:5001/api/user

###

POST http://localhost:5001/api/user
Content-Type: application/json

{
  "firstname": "regigera mig",
  "lastname": "hejsan svejsan",
  "password": "123",
   "address": {
     "street": "Åkannavägen",
     "zipcode": 43540,
     "city": "Mölnlycke"
   }
}

###

PUT http://localhost:5001/api/user/628a78e57940ae5178dd6340
Content-Type: application/json

{

  "firstname": "jag är regigerad nu!",
  "lastname": "hejsan svejsaneee",
  "password": "123",
   "address": {
     "street": "Åkannavägen",
     "zipcode": 43540,
     "city": "Mölnlycke"
   }
  
}

###

DELETE http://localhost:5001/api/user/628a78e57940ae5178dd6340
