http://localhost:5001/api/product

### Get specific product
GET http://localhost:5001/api/product/id

### register new product

POST http://localhost:5001/api/product 
Content-Type: application/json

{
    "name": "product 1", 
    "price": "20", 
    "category":"ugly", 
    "quantity": "3",
    "details": "this is a uggly duck",
    "images": "null"
}

###  update product

PUT http://localhost:5001/api/product/62875b36861fb7a34a6cd375 
Content-Type: application/json

{
    "name": "product 1", 
    "price": "25", 
    "category":"ugly", 
    "quantity": "3",
    "details": "this is a uggly duck",
    "images": "null"
}

### Delete product 
DELETE http://localhost:5001/api/product/62875a9f647863fa4231c91b
