http://localhost:5001/api/product

### Get specific product (get the id from product you want to find)
GET http://localhost:5001/api/product/6295cc33bad9f5114e123f84

### register new product

POST http://localhost:5001/api/product 
Content-Type: application/json

{
    "name": "product 1", 
    "price": "20", 
    "category":"Kända", 
    "quantity": "3",
    "details": "this is a uggly duck",
    "imageId": "6295cc2cbad9f5114e123f81"
}

###  update product (get the id from product you want to update)

PUT http://localhost:5001/api/product/id 
Content-Type: application/json

{
    "name": "product 1", 
    "price": "25", 
    "category":"Kända", 
    "quantity": "3",
    "details": "this is a uggly duck",
    "imageId": "6295cc2cbad9f5114e123f81"
}

### Delete product (get the id from product you want to delete)
DELETE http://localhost:5001/api/product/id
