GET http://localhost:5001/api/delivery

###

POST http://localhost:5001/api/delivery
Content-Type: application/json

{
}

###

PUT http://localhost:5001/api/delivery/1234
Content-Type: application/json

{  
}

###

DELETE http://localhost:5001/api/delivery/1234