GET http://localhost:5001/api/delivery

### 6297319850c803c159aa7969 (instabox)
### 629733dcb66ee974442ec4e5 (schenker)
### 6297321550c803c159aa796c (postnord)



POST http://localhost:5001/api/delivery
Content-Type: application/json

{
    "name": "Instabox",
    "altText": "Leverans till box, 1-2 arbetsdagar",
    "price": 29,
    "shippingTime": 2,
    "logoId": "6297319850c803c159aa7969"
}

###

PUT http://localhost:5001/api/delivery/628b990a29b0b11dbb595342
Content-Type: application/json

{  
    "name": "Bring",
    "price": 0,
    "shippingTime": 72
}

###

DELETE http://localhost:5001/api/delivery/628c7f57fae0a313dc9192f9
